"""Initial models

Revision ID: 83b7c722a3b0
Revises: 
Create Date: 2026-01-11 18:40:17.241013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83b7c722a3b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types with IF NOT EXISTS - using SQLAlchemy's auto-generated names (lowercase, no underscore)
    op.execute("DO $$ BEGIN CREATE TYPE themetype AS ENUM ('light', 'dark', 'system'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE unitpreference AS ENUM ('metric', 'imperial'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('theme_preference', sa.Enum('light', 'dark', 'system', name='themetype', create_type=False), nullable=False),
    sa.Column('unit_preference', sa.Enum('metric', 'imperial', name='unitpreference', create_type=False), nullable=False),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('nutritional_info_per_100g', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('common_package_sizes', postgresql.ARRAY(sa.Numeric(precision=10, scale=2)), nullable=False),
    sa.Column('standard_unit', sa.String(length=20), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('perishability', sa.String(length=20), nullable=False),
    sa.Column('storage_requirements', sa.Text(), nullable=True),
    sa.Column('unit_conversions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_category', 'products', ['category'], unique=False)
    op.create_index('idx_product_perishability', 'products', ['perishability'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('meal_types', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('cuisine_type', sa.String(length=50), nullable=True),
    sa.Column('dietary_tags', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('total_servings', sa.Float(), nullable=False),
    sa.Column('serving_size_unit', sa.String(length=20), nullable=True),
    sa.Column('serving_size_value', sa.Float(), nullable=True),
    sa.Column('nutritional_info_per_serving', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipe_dietary_tags', 'recipes', ['dietary_tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_recipe_meal_types', 'recipes', ['meal_types'], unique=False, postgresql_using='gin')
    op.create_index('idx_recipe_popularity', 'recipes', ['popularity_score'], unique=False)
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('target_calories_per_day', sa.Integer(), nullable=False),
    sa.Column('target_protein_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_carbs_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_fat_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('user_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optimization_status', sa.String(length=50), nullable=False),
    sa.Column('algorithm_execution_time_s', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_food_waste_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('waste_reduction_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estimated_total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meal_plan_created_at', 'meal_plans', ['created_at'], unique=False)
    op.create_index('idx_meal_plan_status', 'meal_plans', ['optimization_status'], unique=False)
    op.create_index('idx_meal_plan_user_id', 'meal_plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_meal_plans_created_at'), 'meal_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_meal_plans_id'), 'meal_plans', ['id'], unique=False)
    op.create_index(op.f('ix_meal_plans_optimization_status'), 'meal_plans', ['optimization_status'], unique=False)
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_unit', sa.String(length=20), nullable=False),
    sa.Column('is_essential', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'product_id', name='uq_recipe_product')
    )
    op.create_index('idx_recipe_ingredient_product', 'recipe_ingredients', ['product_id'], unique=False)
    op.create_index('idx_recipe_ingredient_recipe', 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_product_id'), 'recipe_ingredients', ['product_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('user_ingredient_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('preference_type', sa.String(length=20), nullable=False),
    sa.Column('quantity_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_ingredient_preferences_product_id', 'user_ingredient_preferences', ['product_id'], unique=False)
    op.create_index('idx_user_ingredient_preferences_user_id', 'user_ingredient_preferences', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_ingredient_preferences_user_id'), 'user_ingredient_preferences', ['user_id'], unique=False)
    op.create_table('daily_menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('menu_date', sa.Date(), nullable=False),
    sa.Column('actual_calories', sa.Integer(), nullable=False),
    sa.Column('actual_protein_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_carbs_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_fat_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_menu_day_number', 'daily_menus', ['day_number'], unique=False)
    op.create_index('idx_daily_menu_meal_plan_id', 'daily_menus', ['meal_plan_id'], unique=False)
    op.create_index(op.f('ix_daily_menus_meal_plan_id'), 'daily_menus', ['meal_plan_id'], unique=False)
    op.create_table('grocery_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('estimated_total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_total_waste_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_lists_meal_plan_id'), 'grocery_lists', ['meal_plan_id'], unique=True)
    op.create_table('grocery_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grocery_list_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('required_quantity_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_quantity_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_unit', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('estimated_item_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_item_waste_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grocery_list_id'], ['grocery_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grocery_items_grocery_list_id', 'grocery_items', ['grocery_list_id'], unique=False)
    op.create_index('idx_grocery_items_product_id', 'grocery_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_grocery_items_grocery_list_id'), 'grocery_items', ['grocery_list_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('daily_menu_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('servings', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('calculated_nutritional_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['daily_menu_id'], ['daily_menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meals_daily_menu_id', 'meals', ['daily_menu_id'], unique=False)
    op.create_index('idx_meals_recipe_id', 'meals', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_meals_daily_menu_id'), 'meals', ['daily_menu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meals_daily_menu_id'), table_name='meals')
    op.drop_index('idx_meals_recipe_id', table_name='meals')
    op.drop_index('idx_meals_daily_menu_id', table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_grocery_items_grocery_list_id'), table_name='grocery_items')
    op.drop_index('idx_grocery_items_product_id', table_name='grocery_items')
    op.drop_index('idx_grocery_items_grocery_list_id', table_name='grocery_items')
    op.drop_table('grocery_items')
    op.drop_index(op.f('ix_grocery_lists_meal_plan_id'), table_name='grocery_lists')
    op.drop_table('grocery_lists')
    op.drop_index(op.f('ix_daily_menus_meal_plan_id'), table_name='daily_menus')
    op.drop_index('idx_daily_menu_meal_plan_id', table_name='daily_menus')
    op.drop_index('idx_daily_menu_day_number', table_name='daily_menus')
    op.drop_table('daily_menus')
    op.drop_index(op.f('ix_user_ingredient_preferences_user_id'), table_name='user_ingredient_preferences')
    op.drop_index('idx_user_ingredient_preferences_user_id', table_name='user_ingredient_preferences')
    op.drop_index('idx_user_ingredient_preferences_product_id', table_name='user_ingredient_preferences')
    op.drop_table('user_ingredient_preferences')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_product_id'), table_name='recipe_ingredients')
    op.drop_index('idx_recipe_ingredient_recipe', table_name='recipe_ingredients')
    op.drop_index('idx_recipe_ingredient_product', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_optimization_status'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_id'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_created_at'), table_name='meal_plans')
    op.drop_index('idx_meal_plan_user_id', table_name='meal_plans')
    op.drop_index('idx_meal_plan_status', table_name='meal_plans')
    op.drop_index('idx_meal_plan_created_at', table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_index('idx_recipe_popularity', table_name='recipes')
    op.drop_index('idx_recipe_meal_types', table_name='recipes', postgresql_using='gin')
    op.drop_index('idx_recipe_dietary_tags', table_name='recipes', postgresql_using='gin')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index('idx_product_perishability', table_name='products')
    op.drop_index('idx_product_category', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    unit_system_type = postgresql.ENUM('metric', 'imperial', name='unit_system_type')
    theme_type = postgresql.ENUM('light', 'dark', 'system', name='theme_type')
    unit_system_type.drop(op.get_bind(), checkfirst=True)
    theme_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
